
services:
### Services in LWAN ########
  database:
    hostname: database
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MARIADB_USER=mgbox
      - MARIADB_PASSWORD=mgbox
      - MARIADB_DATABASE=mgbox
    volumes:
      - $PWD/mysql:/var/lib/mysql
    networks: 
      - lan

  mgbox: 
    hostname: mgbox
    image: missancarell/mgbox:v0.3
    restart: unless-stopped
    privileged: true
    command: init
    post_start:
      - command: /bin/sh -c "/usr/mgbox/mgbox_init.sh"
        privileged: true
    ports:
      # - 6422:22
      # - 6443:443
      - 4200:4200
    networks:
      - lan
      - wan
    
# ### Tester in WAN ########
#   tester: 
#     hostname: tester
#     image: missancarell/mgbox:v0.2
#     restart: unless-stopped
#     command: /bin/sh -c "while true; do sleep 10; done"
#     depends_on:
#       - mgbox
#     networks:
#       - wan

### VMs in WAN ########
  vm1: 
    hostname: vm1
    image: missancarell/ubuntu:v0.2
    restart: unless-stopped
    privileged: true
    ports:
      - 6221:22
    depends_on:
      - mgbox
    networks:
      - wan
  vm2: 
    hostname: vm2
    image: missancarell/ubuntu:v0.2
    restart: unless-stopped
    privileged: true
    ports:
      - 6222:22
    command: init
    depends_on:
      - mgbox
    networks: 
      - wan
  vm3: 
    hostname: vm3
    image: missancarell/ubuntu:v0.2
    restart: unless-stopped
    privileged: true
    command: init
    ports:
      - 6223:22
    depends_on:
      - mgbox
    networks: 
      - wan
  vm4: 
    hostname: vm4
    image: missancarell/ubuntu:v0.2
    restart: unless-stopped
    privileged: true
    command: init
    ports:
      - 6224:22
    depends_on:
      - mgbox
    networks: 
      - wan

networks:
  lan:
    driver: bridge
  wan:
    driver: bridge
