
services:
### Services in LWAN ########
  database:
    hostname: database
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MARIADB_USER=mgbox
      - MARIADB_PASSWORD=mgbox
      - MARIADB_DATABASE=mgbox
    networks: 
      - lan

  mgbox: 
    hostname: mgbox
    image: missan/ubuntu:dev
    privileged: true
    command: init
    post_start:
      # - command: /bin/sh -c "sleep 3; /bin/firewall-cmd --add-icmp-block-inversion"
      - command: /bin/sh -c "/usr/mgbox/mgbox_init.sh"
      # - command: /bin/sh -c "echo chmod a+x /home/mgbox/mgbox.sh"
      # - command: /bin/sh -c "echo /home/mgbox/mgbox.sh >> /home/mgbox/.bashrc"
      # - command: /bin/sh -c "echo exit 0 >> /home/mgbox/.bashrc"
        privileged: true
    volumes:
      - $PWD/mgbox_init.sh:/usr/mgbox/mgbox_init.sh:rx
      - $PWD/mgbox_cli.sh:/usr/mgbox/mgbox_cli.sh:rx
      - $PWD/mgbox_server.sh:/usr/mgbox/mgbox_server.sh:rx
      - $PWD/mgbox_client.sh:/usr/mgbox/mgbox_client.sh:rx
      - $PWD/mgbox_client_setup.sh:/usr/mgbox/mgbox_client_setup.sh:rx
      - $PWD/utils.sh:/usr/mgbox/utils.sh:rx
      # - $PWD/missan/xbin:/usr/bin/hc:rx
      # - $PWD/missan/xbin:/usr/bin/ptable:rx
    networks: 
      - lan
      - wan
    
### Tester in WAN ########
  tester: 
    hostname: tester
    image: missan/ubuntu:dev
    # image: newzyer/xbin
    command: /bin/sh -c "while true; do sleep 10; done"
    depends_on:
      - mgbox
    networks: 
      - wan

### VMs in WAN ########
  vm1: 
    hostname: vm1
    image: missan/ubuntu:dev
    privileged: true
    depends_on:
      - mgbox
    networks: 
      - wan
    volumes:
      - $PWD/utils.sh:/usr/mgbox/utils.sh:rx
      - $PWD/mgbox_client.sh:/usr/mgbox/mgbox_client.sh:rx
  vm2: 
    hostname: vm2
    image: missan/ubuntu:dev
    privileged: true
    command: init
    depends_on:
      - mgbox
    networks: 
      - wan
  vm3: 
    hostname: vm3
    image: missan/ubuntu:dev
    privileged: true
    command: init
    depends_on:
      - mgbox
    networks: 
      - wan
  vm4: 
    hostname: vm4
    image: missan/ubuntu:dev
    privileged: true
    command: init
    depends_on:
      - mgbox
    networks: 
      - wan

networks:
  lan:
    driver: macvlan
  wan:
    driver: macvlan
